-- Skrypt źródłowy: kursySiedziba.sql
-- Schema: SIEDZIBA (odpowiednik bazy11a - siedziba w Bydgoszczy)

CREATE TABLE wykladowcy(wykladowca_id number(6) primary key,imie varchar2(20) NOT NULL,nazwisko varchar2(30) NOT NULL,stawka decimal(5,2));
CREATE TABLE kursanci(kursant_id number(6) PRIMARY KEY,imie varchar2(20) NOT NULL,nazwisko varchar2(30) NOT NULL);
CREATE TABLE rodzaje(rodzaj_id number(3) primary key,nazwa varchar2(30) NOT NULL,godz number(3) NOT NULL,cena decimal(6,2));
CREATE TABLE kursy(kurs_id number(6) primary key,rodzaj_id number(6) NOT NULL,wykladowca_id number(6));
CREATE TABLE umowy(umowa_id number(6) primary key,kursant_id number(6),kurs_id number(6),miasto varchar(20));
ALTER TABLE kursy ADD CONSTRAINT kursy_rodzaje_fkey FOREIGN KEY (rodzaj_id) REFERENCES rodzaje(rodzaj_id);
ALTER TABLE kursy ADD CONSTRAINT kursy_wykladowcy_fkey FOREIGN KEY (wykladowca_id) REFERENCES wykladowcy(wykladowca_id);

-- 19 wykładowców
INSERT INTO WYKLADOWCY VALUES (1,'PRZEMYSLAW','KRAJEWSKI',80);
INSERT INTO WYKLADOWCY VALUES (2,'LEO','ADAMSKI',90);
INSERT INTO WYKLADOWCY VALUES (3,'NATANIEL','SIKORSKI',100);
INSERT INTO WYKLADOWCY VALUES (4,'RYSZARD','MROZ',80);
INSERT INTO WYKLADOWCY VALUES (5,'FELIKS','LASKOWSKI',70);
INSERT INTO WYKLADOWCY VALUES (6,'MAREK','ZIOLKOWSKI',100);
INSERT INTO WYKLADOWCY VALUES (7,'RADOSLAW','GAJEWSKI',100);
INSERT INTO WYKLADOWCY VALUES (8,'KONRAD','SZULC',80);
INSERT INTO WYKLADOWCY VALUES (9,'ALEX','MAKOWSKI',80);
INSERT INTO WYKLADOWCY VALUES (10,'DORIAN','BARANOWSKI',70);
INSERT INTO WYKLADOWCY VALUES (11,'JULIUSZ','CZERWINSKI',70);
INSERT INTO WYKLADOWCY VALUES (12,'JEREMI','SZYMCZAK',80);
INSERT INTO WYKLADOWCY VALUES (13,'ALEKS','PRZYBYLSKI',100);
INSERT INTO WYKLADOWCY VALUES (14,'REMIGIUSZ','KACZMARCZYK',120);
INSERT INTO WYKLADOWCY VALUES (15,'FLORIAN','BRZEZINSKI',100);
INSERT INTO WYKLADOWCY VALUES (16,'SAMUEL','BLASZCZYK',90);
INSERT INTO WYKLADOWCY VALUES (17,'ARKADIUSZ','ANDRZEJEWSKI',90);
INSERT INTO WYKLADOWCY VALUES (18,'GRACJAN','CIESLAK',80);
INSERT INTO WYKLADOWCY VALUES (19,'ALBERT','BOROWSKI',100);

-- 85 kursantów
INSERT INTO KURSANCI VALUES (1,'LEOKADIA','NOWAK');
INSERT INTO KURSANCI VALUES (2,'NELA','KOWALSKA');
INSERT INTO KURSANCI VALUES (3,'EMMA','WISNIEWSKA');
INSERT INTO KURSANCI VALUES (4,'JULITA','WOJCIK');
INSERT INTO KURSANCI VALUES (5,'OKTAWIA','KOWALCZYK');
INSERT INTO KURSANCI VALUES (6,'PAULA','KAMINSKA');
INSERT INTO KURSANCI VALUES (7,'REGINA','LEWANDOWSKA');
INSERT INTO KURSANCI VALUES (8,'SABINA','ZIELINSKA');
INSERT INTO KURSANCI VALUES (9,'SANDRA','SZYMANSKA');
INSERT INTO KURSANCI VALUES (10,'FELICJA','DABROWSKA');
INSERT INTO KURSANCI VALUES (11,'KONSTANCJA','WOZNIAK');
INSERT INTO KURSANCI VALUES (12,'MELANIA','KOZLOWSKA');
INSERT INTO KURSANCI VALUES (13,'MIROSLAWA','JANKOWSKA');
INSERT INTO KURSANCI VALUES (14,'SOFIA','MAZUR');
INSERT INTO KURSANCI VALUES (15,'BRONISLAWA','KWIATKOWSKA');
INSERT INTO KURSANCI VALUES (16,'CELINA','WOJCIECHOWSKA');
INSERT INTO KURSANCI VALUES (17,'GENOWEFA','KRAWCZYK');
INSERT INTO KURSANCI VALUES (18,'IZABELLA','KACZMAREK');
INSERT INTO KURSANCI VALUES (19,'JASMINA','PIOTROWSKA');
INSERT INTO KURSANCI VALUES (20,'MAGDA','GRABOWSKA');
INSERT INTO KURSANCI VALUES (21,'MARIE','PAWLOWSKA');
INSERT INTO KURSANCI VALUES (22,'MARIKA','MICHALSKA');
INSERT INTO KURSANCI VALUES (23,'OLIVIA','KROL');
INSERT INTO KURSANCI VALUES (24,'ROKSANA','ZAJAC');
INSERT INTO KURSANCI VALUES (25,'WALENTYNA','WIECZOREK');
INSERT INTO KURSANCI VALUES (26,'WIESLAWA','JABLONSKA');
INSERT INTO KURSANCI VALUES (27,'AURORA','WROBEL');
INSERT INTO KURSANCI VALUES (28,'DAGMARA','NOWAKOWSKA');
INSERT INTO KURSANCI VALUES (29,'ELENA','MAJEWSKA');
INSERT INTO KURSANCI VALUES (30,'ELIZABETH','OLSZEWSKA');
INSERT INTO KURSANCI VALUES (31,'HONORATA','ADAMCZYK');
INSERT INTO KURSANCI VALUES (32,'ILONA','JAWORSKA');
INSERT INTO KURSANCI VALUES (33,'JAGNA','MALINOWSKA');
INSERT INTO KURSANCI VALUES (34,'JULIANNA','STEPIEN');
INSERT INTO KURSANCI VALUES (35,'LUIZA','DUDEK');
INSERT INTO KURSANCI VALUES (36,'VIKTORIA','GORSKA');
INSERT INTO KURSANCI VALUES (37,'WLADYSLAWA','NOWICKA');
INSERT INTO KURSANCI VALUES (38,'ZANETA','WITKOWSKA');
INSERT INTO KURSANCI VALUES (39,'ADA','PAWLAK');
INSERT INTO KURSANCI VALUES (40,'ELEONORA','SIKORA');
INSERT INTO KURSANCI VALUES (41,'ELWIRA','WALCZAK');
INSERT INTO KURSANCI VALUES (42,'EULALIA','RUTKOWSKA');
INSERT INTO KURSANCI VALUES (43,'EVA','MICHALAK');
INSERT INTO KURSANCI VALUES (44,'FILOMENA','SZEWCZYK');
INSERT INTO KURSANCI VALUES (45,'FLORENTYNA','OSTROWSKA');
INSERT INTO KURSANCI VALUES (46,'HENRYKA','BARAN');
INSERT INTO KURSANCI VALUES (47,'INGA','TOMASZEWSKA');
INSERT INTO KURSANCI VALUES (48,'LEA','ZALEWSKA');
INSERT INTO KURSANCI VALUES (49,'LILA','PIETRZAK');
INSERT INTO KURSANCI VALUES (50,'LILLA','WRUBLEWSKA');
INSERT INTO KURSANCI VALUES (51,'LIVIA','JASINSKA');
INSERT INTO KURSANCI VALUES (52,'LUDWIKA','MARCINIAK');
INSERT INTO KURSANCI VALUES (53,'MALINA','JAKUBOWSKA');
INSERT INTO KURSANCI VALUES (54,'MARCELA','SADOWSKA');
INSERT INTO KURSANCI VALUES (55,'MARCJANNA','ZAWADZKA');
INSERT INTO KURSANCI VALUES (56,'MIRA','DUDA');
INSERT INTO KURSANCI VALUES (57,'NAOMI','WLODARCZYK');
INSERT INTO KURSANCI VALUES (58,'NEL','BAK');
INSERT INTO KURSANCI VALUES (59,'NICOLA','CHMIELEWSKA');
INSERT INTO KURSANCI VALUES (60,'ROMA','BORKOWSKA');
INSERT INTO KURSANCI VALUES (61,'ROSE','WILK');
INSERT INTO KURSANCI VALUES (62,'VIOLETTA','SOKOLOWSKA');
INSERT INTO KURSANCI VALUES (63,'WALERIA','SZCZEPANSKA');
INSERT INTO KURSANCI VALUES (64,'WIOLETA','SAWICKA');
INSERT INTO KURSANCI VALUES (65,'ALDONA','LIS');
INSERT INTO KURSANCI VALUES (66,'AMANDA','KUCHARSKA');
INSERT INTO KURSANCI VALUES (67,'ANDZELIKA','MACIEJEWSKA');
INSERT INTO KURSANCI VALUES (68,'BERNADETA','KALINOWSKA');
INSERT INTO KURSANCI VALUES (69,'BERNADETTA','MAZUREK');
INSERT INTO KURSANCI VALUES (70,'DOBROSLAWA','WYSOCKA');
INSERT INTO KURSANCI VALUES (71,'DOMICELA','KUBIAK');
INSERT INTO KURSANCI VALUES (72,'ESTERA','KOLODZIEJ');
INSERT INTO KURSANCI VALUES (73,'FLORA','CZARNECKA');
INSERT INTO KURSANCI VALUES (74,'GLORIA','KAZMIERCZAK');
INSERT INTO KURSANCI VALUES (75,'HALSZKA','URBANSKA');
INSERT INTO KURSANCI VALUES (76,'HIACYNTA','SOBCZAK');
INSERT INTO KURSANCI VALUES (77,'JOWITA','GLOWACKA');
INSERT INTO KURSANCI VALUES (78,'KLEMENTYNA','KRAJEWSKA');
INSERT INTO KURSANCI VALUES (79,'LAILA','KRUPA');
INSERT INTO KURSANCI VALUES (80,'LORENA','SIKORSKA');
INSERT INTO KURSANCI VALUES (81,'MARIETTA','ZAKRZEWSKA');
INSERT INTO KURSANCI VALUES (82,'MIRIAM','WASILEWSKA');
INSERT INTO KURSANCI VALUES (83,'NAWOJKA','ZIOLKOWSKA');
INSERT INTO KURSANCI VALUES (84,'OLIMPIA','LASKOWSKA');
INSERT INTO KURSANCI VALUES (85,'OTYLIA','GAJEWSKA');

-- 8 rodzajów kursów językowych
INSERT INTO RODZAJE VALUES (1,'angielski',80,1200);
INSERT INTO RODZAJE VALUES (2,'wloski',90,890);
INSERT INTO RODZAJE VALUES (3,'francuski',80,1200);
INSERT INTO RODZAJE VALUES (4,'grecki',70,970);
INSERT INTO RODZAJE VALUES (5,'japonski',60,670);
INSERT INTO RODZAJE VALUES (6,'czeski',70,940);
INSERT INTO RODZAJE VALUES (7,'rosyjski',80,850);
INSERT INTO RODZAJE VALUES (8,'niemiecki',80,1100);

-- 8 kursów
INSERT INTO KURSY VALUES (1,1,1);
INSERT INTO KURSY VALUES (2,2,2);
INSERT INTO KURSY VALUES (3,2,2);
INSERT INTO KURSY VALUES (4,3,3);
INSERT INTO KURSY VALUES (5,4,4);
INSERT INTO KURSY VALUES (6,5,6);
INSERT INTO KURSY VALUES (7,6,7);
INSERT INTO KURSY VALUES (8,7,9);

-- Umowy (85 siedziby + 81 filii = 166 rekordów)
INSERT INTO UMOWY VALUES (1,1,1,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (2,2,1,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (3,3,1,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (4,4,1,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (5,5,1,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (6,6,1,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (7,7,1,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (8,8,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (9,9,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (10,10,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (11,11,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (12,12,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (13,13,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (14,14,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (15,15,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (16,16,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (17,17,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (18,18,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (19,19,2,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (20,20,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (21,21,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (22,22,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (23,23,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (24,24,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (25,25,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (26,26,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (27,27,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (28,28,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (29,29,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (30,30,3,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (31,31,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (32,32,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (33,33,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (34,34,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (35,35,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (36,36,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (37,37,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (38,38,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (39,39,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (40,40,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (41,41,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (42,42,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (43,43,4,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (44,44,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (45,45,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (46,46,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (47,47,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (48,48,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (49,49,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (50,50,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (51,51,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (52,52,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (53,53,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (54,54,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (55,55,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (56,56,5,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (57,57,6,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (58,58,6,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (59,59,6,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (60,60,6,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (61,61,6,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (62,62,6,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (63,63,6,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (64,64,6,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (65,65,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (66,66,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (67,67,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (68,68,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (69,69,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (70,70,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (71,71,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (72,72,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (73,73,7,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (74,74,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (75,75,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (76,76,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (77,77,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (78,78,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (79,79,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (80,80,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (81,81,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (82,82,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (83,83,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (84,84,8,'BYDGOSZCZ'); INSERT INTO UMOWY VALUES (85,85,8,'BYDGOSZCZ');
-- Umowy filii (SZCZECIN)
INSERT INTO UMOWY VALUES (86,1000,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (87,1001,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (88,1002,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (89,1003,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (90,1004,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (91,1005,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (92,1006,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (93,1007,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (94,1008,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (95,1009,101,'SZCZECIN'); INSERT INTO UMOWY VALUES (96,1010,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (97,1011,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (98,1012,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (99,1013,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (100,1014,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (101,1015,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (102,1016,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (103,1017,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (104,1018,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (105,1019,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (106,1020,102,'SZCZECIN'); INSERT INTO UMOWY VALUES (107,1021,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (108,1022,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (109,1023,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (110,1024,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (111,1025,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (112,1026,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (113,1027,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (114,1028,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (115,1029,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (116,1030,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (117,1031,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (118,1032,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (119,1033,103,'SZCZECIN'); INSERT INTO UMOWY VALUES (120,1034,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (121,1035,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (122,1036,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (123,1037,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (124,1038,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (125,1039,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (126,1040,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (127,1041,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (128,1042,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (129,1043,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (130,1044,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (131,1045,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (132,1046,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (133,1047,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (134,1048,104,'SZCZECIN'); INSERT INTO UMOWY VALUES (135,1049,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (136,1050,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (137,1051,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (138,1052,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (139,1053,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (140,1054,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (141,1055,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (142,1056,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (143,1057,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (144,1058,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (145,1059,105,'SZCZECIN'); INSERT INTO UMOWY VALUES (146,1060,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (147,1061,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (148,1062,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (149,1063,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (150,1064,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (151,1065,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (152,1066,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (153,1067,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (154,1068,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (155,1069,106,'SZCZECIN'); INSERT INTO UMOWY VALUES (156,1070,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (157,1071,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (158,1072,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (159,1073,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (160,1074,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (161,1075,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (162,1076,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (163,1077,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (164,1078,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (165,1079,107,'SZCZECIN'); INSERT INTO UMOWY VALUES (166,1080,107,'SZCZECIN');

COMMIT;
